helm/chart-releaser-action

cr.sh

Prevents action fails when there are directories detected that do not contain charts (e.g. `.github`)
as proposed in #12 
feedback welcome
fixes #12

Ignore directories with missing Chart.yaml

---

README.md
cr.sh

Per the issue linked in the README, `CR_TOKEN` should no longer be necessary: https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/m-p/31283/highlight/true#M751
fixes: #28

Use provided GITHUB_TOKEN instead of custom PAT

---

README.md
action.yml
cr.sh

These coincidentally are both ready for v1.0.0 (not that the action and cr will normally be the same version, but after this PR they will be)
Signed-off-by: Scott Rigby <scott@r6by.com>

Bump chart-releaser to v1.0.0 and prep chart-releaser-action for v1.0.0

---

cr.sh

At present, the tip of the default branch is tagged with the release instead of the branch target for release. This is not ideal if we want to make releases out of non-default branches. Use the current commit ID as the input when invoking `cr upload` so that the releases are tagged correctly.

Tag release with commit hash of the tip of current branch

---

cr.sh

Fix handling of deeply nested charts_dir

---

cr.sh

chart-releaser is now able to package charts and to
push the index.yaml to the configured branch.
Signed-off-by: Reinhard Nägele <unguiculus@gmail.com>

Use built-in package and upload functionality

---

README.md

Use current latest released version of the action in the README and not a future unreleased one :)

Fix action version in README

---

README.md
action.yml
cr.sh

/assign @unguiculus @davidkarlsen

chart-releaser: update to use release 1.2.0

---

cr.sh

Fixes an issue with `depth` when `charts_dir` is set to `.`
This is the same fix identified in PR #62, and contains @montek 's [update recommendation](https://github.com/helm/chart-releaser-action/pull/62#pullrequestreview-605848446), as it seems the PR has become stale.
Closes issue #61 and PR #62.

Fixes an issue with chart_depth when charts_dir is .

---

README.md

Remove reference to github api, add documentation for chart-releaser cli

---

README.md

I found that there were some instructions missing from the prerequisites that weren't very straightforward. Also added some notes about where and how `index.yaml` is maintained.

docs: Add prerequisite to README

---

cr.sh

Currently, only when the `cr` is installed the PATH env is updated with the cache directory, resulting in a working behavior for the first time but in consequents runs in the following error:
```
Looking up latest tag...
Discovering changed charts since 'test-0.0.8'...
Packaging chart 'charts/test'...
/tmp/_work/B5Gz2/_actions/helm/chart-releaser-action/v1.2.1/cr.sh: line 243: cr: command not found
Error: Process completed with exit code 127.
```
This might not be a problem in stateless runners since there the `cr` is always installed, but for stateful ones, its easy to replicate.

fix: cache directory path always in PATH env

---

.github/workflows/test-action.yml
README.md
action.yml
cr.sh

- update chart-releaser to v1.3.0
- add workflow to perform simple validate of the action

update chart-releaser to v1.3.0

---

.github/workflows/test-action.yml
README.md
action.yml
cr.sh

- update chart release action to use CR release v1.4.0

update chart release action to use CR release v1.4.0

---

README.md
action.yml
cr.sh

bump cr to v1.4.1

---

README.md
action.yml
cr.sh

This change resolves #108 by adding the option to skip the packaging step altogether.

Skip packaging option - resolves #108

---

action.yml
cr.sh

The `--charts-repo` option is no longer used, since https://github.com/helm/chart-releaser/pull/144. This PR removes it from the action as well.
Fixes #122.

Remove deprecated charts-repo-url option

---

cr.sh

helm/chart-releaser-action does not work on actions triggered by a tag because the `lookup_changed_charts` will never find differences in the charts. The problem is that `lookup_latest_tag` returns the tag that triggered the action, which is the current commit analyzed by `lookup_changed_charts`.
This simple solution skips the current (tagged) commit when searching for tags.
This is currently working for me. Others have requested it as well (https://github.com/helm/chart-releaser-action/issues/60).
Any feedback appreciated. Thanks

Support actions triggered by a tag

---

action.yml
cr.sh

closes #70 (following the last comment https://github.com/helm/chart-releaser-action/issues/70#issuecomment-919904216)

Add flag `skip-existing` to skip upload if release exists

---

README.md

`charts_repo_url` is no longer supported, so should be removed from readme

Remove `charts_repo_url` from readme

---

README.md

As `charts_repo_url` option has been deprecated: https://github.com/helm/chart-releaser-action/pull/123, reference of `charts_repo_url` in `REAMDE.md` documentation should also be removed to prevent further usage.
For more information, follow: https://github.com/helm/chart-releaser-action/pull/123#issuecomment-1452649079, https://github.com/helm/chart-releaser-action/pull/123#issuecomment-1503020990
---
Updates: 2023.04.18
`mark_as_latest` option also seems to be deprecated too. Removed `mark_as_latest` in doc and codes as well.

Remove deprecated `charts_repo_url` option in documentation

---

README.md
action.yml
cr.sh

Added flag `--package-with-index` implemented in https://github.com/helm/chart-releaser/pull/304.
Implements #147

Added: --packages-with-index parameter

---

README.md
action.yml
cr.sh

Ref:
helm/chart-releaser@378f527
helm/chart-releaser@cb0563b

Add `--pages-branch` parameter

---

.github/dependabot.yml
.github/workflows/test-action.yml
README.md
action.yml
cr.sh

- bump cr to 1.6.1 and add dependabot config

bump cr to 1.6.1 and add dependabot config

---

README.md
action.yml
cr.sh

This PR introduces a new feature that allows skipping the `upload_index` parts in this action. The main motivation behind this change is to enable the use of OCI-based repositories for Helm with the Github Container Registry without managing the upload process of the `index.yaml` file.
Changes Made:
- Updated `README.md`: Added information about the new `--skip-upload` option and its purpose.
- Updated `action.yaml`: Added the skip_upload input parameter to the action file.
- Updated `cr.sh`:
* Added the `--skip-upload` option to the script's usage information.
* Modified the `main()` function to respect the skip_upload option.
* ~~Ensured that `update_index` is only called if the `skip_upload` option is not set.~~ This is handled directly in the `update_index` function now.
* Handled the …

Add --skip-upload input with latest helm/chart-releaser-action

---

README.md

Hello 👋 
Simple change in the readme.md, to reflect the deprecation of actions/checkout@v3
The change was made in the test_action in a917fd1, so I assume it works well.

Bump actions/checkout from v3 to v4 in example action in README.md

---

action.yml
cr.sh

This fixes https://github.com/helm/chart-releaser-action/issues/207.
This is a non-breaking change that adds support for ARM64 Github Runners. If the runners architecture is `ARM64` it will install the `linux_arm64` version of the `chart-releaser` binary, otherwise it will default to `linux_amd64`.

Adding support for ARM Runners

---

cr.sh

The chart_version output was written regardless of whether the latest_tag variable was defined. The latest_tag variable is only defined if skip_packaging is not set. This leads to issue #171.
Setting skip_packaging implies that an external process takes care of packaging the chart and setting the chart version. There is thus no need to write the chart_version output as it should already be known.
Closes #171

Write chart_version only if latest_tag is defined
